name: Notifier
on:
  pull_request_review:
    types: [edited, dismissed, submitted]
  
jobs:
  Notifier:
    name: Notifier
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get README.md
        run: |
          git fetch --quiet
          diff=$(git diff origin/master HEAD --name-only)
          diff="${changed//'%'/'%25'}"
          diff="${changed//$'\n'/'%0A'}"
          diff="${changed//$'\r'/'%0D'}"
          echo "::set-output name=files::$diff"
        id: get-diff
      - name: run python
        uses: ./
        with:
          filePath: ${{ steps.get-diff.outputs.files}}
          usernameSecret: ${{ secrets.EMAIL_USERNAME }}
          passwordSecret: ${{ secrets.EMAIL_PASSWORD }}
          domainSecret: ${{ secrets.EMAIL_DOMAIN }}
